capture confirm global REPLICATION_ROOT
if _rc {
    do "code/00_setup/config.do"
}
else if "${REPLICATION_ROOT}" == "" {
    do "code/00_setup/config.do"
}
/********************************************************************
 Robustness checks for exclusion restriction
 Chinese import competition and Turkish manufacturing markups

 Constructs:
   1. High-income global demand control
   2. Turkish export-demand control
   3. IV robustness table
   4. Pre-trend balance checks
   5. Residualized output-IV robustness

 Data-source notes from project inspection:
   - Main panel: Data/data_ready_mec.dta
   - BACI source: RawData/CEPII BACI HS96/BACI_HS96_Y*.csv
       Raw BACI variables are t i j k v q.
   - HS6-ISIC4 concordance: Data/BACI/hs96_isic4_4digit_withshares.dta
       This is generated by the R concordance scripts in dofile construction,
       using concord_hs_isic(..., origin = "HS1", destination = "ISIC4").
       Its weight variable is share.
   - High-income destinations follow dofile construction/4 bartik_instrument.do:
       US, Japan, EU15, South Korea, Australia; numeric country codes listed
       below in Section 2.
********************************************************************/

clear all
set more off
version 17

/********************************************************************
 0. USER SETTINGS
********************************************************************/

*----------------------------
* Paths
*----------------------------
global folder      "$REPLICATION_ROOT"
global main_panel  "$DATA_DERIVED/data_ready_mec.dta"
global baci_data   "$DATA_RAW/CEPII BACI HS96"
global concordance "$DATA_DERIVED/BACI/hs96_isic4_4digit_withshares.dta"
global hi_list     "$DATA_DERIVED/BACI/high_income_bartik_codes.dta"
global output_dir  "$OUTPUT_TABLES"
global data_out    "$DATA_DERIVED/BACI"

capture mkdir "$output_dir"
capture mkdir "$data_out"
capture log close
log using "$LOGS/4_robustness_id.log", replace

*----------------------------
* BACI source settings
*----------------------------
* The project stores full BACI as annual CSVs, not as one combined .dta.
* This do-file maps only high-income-destination trade, which is enough for
* the two demand controls and keeps the raw BACI import manageable.
local baci_is_annual_csv 1
local baci_start 2007
local baci_end   2019
local baci_version "V202501"

*----------------------------
* BACI variable names
*----------------------------
* Raw CEPII BACI HS96 CSV names.
local yearvar     t
local expvar      i
local impvar      j
local hsvar       k
local tradevar    v

*----------------------------
* Concordance variable names
*----------------------------
local conc_hs     hs6
local conc_isic   isic4
local conc_weight share

*----------------------------
* High-income list variable names
*----------------------------
local hi_country  country_code
local hi_flag     high_income

*----------------------------
* Country-code format
*
* The construction do-files use numeric ISO/BACI country codes:
*   China = 156, Turkey = 792
*----------------------------
local china_code  "156"
local turkey_code "792"

*----------------------------
* Base years for Turkish export weights
*----------------------------
local base_start 2007
local base_end   2009

*----------------------------
* Regression settings
*----------------------------
local est_start 2011
local est_end   2019
local pre_cutoff 2011

global X_lag "lleverage lliquidity llnsize l_age l_exporter"

foreach cmd in reghdfe ivreghdfe eststo esttab {
    capture which `cmd'
    if _rc {
        di as error "`cmd' is not installed. Install it before running this do-file."
        exit 199
    }
}

/********************************************************************
 1. HELPER: PREPARE HS6-ISIC4 CONCORDANCE
********************************************************************/

tempfile concord_clean hi_clean baci_mapped ///
         global_demand export_weights dest_demand ///
         export_demand demand_controls main_with_controls

capture confirm file "$data_out/demand_controls_isic4_year.dta"
if !_rc {
    di as txt "Using existing derived demand controls: $data_out/demand_controls_isic4_year.dta"
    use "$data_out/demand_controls_isic4_year.dta", clear
    save "$output_dir/demand_controls_isic4_year.dta", replace
    save `demand_controls', replace
}
else {

use "$concordance", clear

* Standardize HS6 key.
capture confirm numeric variable `conc_hs'
if !_rc {
    gen str6 hs6_key = string(`conc_hs', "%06.0f")
}
else {
    gen str20 _hs_tmp = trim(`conc_hs')
    replace _hs_tmp = subinstr(_hs_tmp, ".", "", .)
    gen str6 hs6_key = substr("000000" + _hs_tmp, strlen("000000" + _hs_tmp) - 5, 6)
    drop _hs_tmp
}

* Standardize ISIC4 variable name.
if "`conc_isic'" != "isic4" {
    rename `conc_isic' isic4
}
capture confirm string variable isic4
if !_rc {
    drop if missing(isic4) | isic4 == "" | isic4 == "NA"
}
else {
    drop if missing(isic4)
}

* Weight handling. The project concordance uses share = Liao/Kim weight.
capture confirm variable `conc_weight'
if _rc {
    gen double concord_weight = 1
}
else {
    rename `conc_weight' concord_weight
    capture destring concord_weight, replace force
}

* Normalize concordance weights within HS6 so that many-to-many allocations
* preserve each product's total value.
bys hs6_key: egen double weight_sum = total(concord_weight)
replace concord_weight = concord_weight / weight_sum if weight_sum > 0
drop weight_sum

keep hs6_key isic4 concord_weight
duplicates drop

save `concord_clean', replace

/********************************************************************
 2. HELPER: PREPARE HIGH-INCOME COUNTRY LIST
********************************************************************/

* The inspected project does not store a separate high-income .dta. The list
* below is the exact importer set used in dofile construction/4 bartik_instrument.do:
* Australia, Austria, Belgium, Denmark, Finland, France, Germany, Greece,
* Ireland, Italy, Japan, South Korea, Luxembourg, Netherlands, Portugal, Spain,
* Sweden, United Kingdom, United States.
clear
input int country_code byte high_income
36  1
40  1
56  1
208 1
246 1
250 1
276 1
300 1
372 1
380 1
392 1
410 1
442 1
528 1
620 1
724 1
752 1
826 1
840 1
end
save "$hi_list", replace

use "$hi_list", clear
keep if `hi_flag' == 1

* Standardize country key.
capture confirm numeric variable `hi_country'
if !_rc {
    gen str10 importer_key = string(`hi_country', "%03.0f")
}
else {
    gen str10 importer_key = upper(trim(`hi_country'))
}

keep importer_key
duplicates drop

save `hi_clean', replace

/********************************************************************
 3. LOAD BACI AND MAP HS6 TO ISIC4
********************************************************************/

local first_baci_year_done 0

forvalues yy = `baci_start'/`baci_end' {
    local raw_file "$baci_data/BACI_HS96_Y`yy'_`baci_version'.csv"
    capture confirm file "`raw_file'"
    if _rc {
        di as error "Missing BACI raw file for `yy': `raw_file'"
        continue
    }

    di as txt "Mapping BACI high-income-destination trade for year `yy'..."
    import delimited "`raw_file'", clear varnames(1)

    * Standardize HS6.
    capture confirm numeric variable `hsvar'
    if !_rc {
        gen str6 hs6_key = string(`hsvar', "%06.0f")
    }
    else {
        gen str20 _hs_tmp = trim(`hsvar')
        replace _hs_tmp = subinstr(_hs_tmp, ".", "", .)
        gen str6 hs6_key = substr("000000" + _hs_tmp, strlen("000000" + _hs_tmp) - 5, 6)
        drop _hs_tmp
    }

    * Standardize exporter and importer country keys.
    capture confirm numeric variable `expvar'
    if !_rc {
        gen str10 exporter_key = string(`expvar', "%03.0f")
    }
    else {
        gen str10 exporter_key = upper(trim(`expvar'))
    }

    capture confirm numeric variable `impvar'
    if !_rc {
        gen str10 importer_key = string(`impvar', "%03.0f")
    }
    else {
        gen str10 importer_key = upper(trim(`impvar'))
    }

    keep `yearvar' exporter_key importer_key hs6_key `tradevar'
    rename `yearvar' year
    rename `tradevar' trade_value

    drop if missing(year, trade_value)
    drop if trade_value < 0

    * All controls use high-income destinations, so filter early.
    merge m:1 importer_key using `hi_clean', keep(match) nogen

    * Map HS6 to ISIC4. The concordance can contain multiple ISIC4 matches
    * per HS6, so use joinby as in the existing construction do-files.
    joinby hs6_key using `concord_clean', unmatched(none)

    * Allocate trade value across ISIC4 using concordance weights.
    gen double trade_isic = trade_value * concord_weight

    keep year exporter_key importer_key isic4 trade_isic
    compress
    if `first_baci_year_done' == 0 {
        save `baci_mapped', replace
        local first_baci_year_done 1
    }
    else {
        append using `baci_mapped'
        save `baci_mapped', replace
    }
}

if `first_baci_year_done' == 0 {
    di as error "No BACI years were loaded. Check $baci_data and baci_version."
    exit 601
}

use `baci_mapped', clear
capture destring isic4, replace force
drop if missing(isic4)
compress
save "$data_out/baci_hi_destinations_mapped_isic4_2007_2019.dta", replace
save `baci_mapped', replace

/********************************************************************
 4. GLOBAL HIGH-INCOME DEMAND CONTROL

 For each ISIC4-year:
   sum high-income imports from all exporters except China and Turkey.

 This absorbs rich-country sectoral demand shocks that might otherwise
 be confounded with China-side supply pressure.
********************************************************************/

use `baci_mapped', clear

* Exclude China and Turkey as exporters.
drop if exporter_key == "`china_code'"
drop if exporter_key == "`turkey_code'"

collapse (sum) GlobalDemand_HI = trade_isic, by(isic4 year)

gen double ln_GlobalDemand_HI = log(GlobalDemand_HI) if GlobalDemand_HI > 0

sort isic4 year
by isic4: gen double dln_GlobalDemand_HI = ln_GlobalDemand_HI - ln_GlobalDemand_HI[_n-1] ///
    if year == year[_n-1] + 1

keep isic4 year GlobalDemand_HI ln_GlobalDemand_HI dln_GlobalDemand_HI
save "$data_out/global_demand_hi_isic4_year.dta", replace
save `global_demand', replace

/********************************************************************
 5. TURKISH EXPORT-DESTINATION WEIGHTS

 omega_jd0 =
   Turkish exports to high-income destination d in sector j during
   2007-2009 divided by Turkish exports to all high-income destinations
   in sector j during 2007-2009.
********************************************************************/

use `baci_mapped', clear

* Keep Turkey as exporter in base years.
keep if exporter_key == "`turkey_code'"
keep if inrange(year, `base_start', `base_end')

collapse (sum) tur_exports_base = trade_isic, by(isic4 importer_key)

bys isic4: egen double total_tur_exports_base = total(tur_exports_base)

gen double omega_jd0 = tur_exports_base / total_tur_exports_base ///
    if total_tur_exports_base > 0

keep isic4 importer_key omega_jd0
drop if missing(omega_jd0)
save "$data_out/turkish_hi_export_weights_2007_2009.dta", replace
save `export_weights', replace

/********************************************************************
 6. DESTINATION-SECTOR DEMAND GROWTH

 Demand_jdt =
   total imports of high-income destination d in sector j
   from all exporters except Turkey.

 Then compute dln_Demand_jdt.
********************************************************************/

use `baci_mapped', clear

* Exclude Turkey as exporter.
drop if exporter_key == "`turkey_code'"

collapse (sum) Demand_jdt = trade_isic, by(isic4 importer_key year)

gen double ln_Demand_jdt = log(Demand_jdt) if Demand_jdt > 0

sort isic4 importer_key year
by isic4 importer_key: gen double dln_Demand_jdt = ln_Demand_jdt - ln_Demand_jdt[_n-1] ///
    if year == year[_n-1] + 1

keep isic4 importer_key year Demand_jdt ln_Demand_jdt dln_Demand_jdt
save "$data_out/hi_destination_sector_demand_growth.dta", replace
save `dest_demand', replace

/********************************************************************
 7. TURKISH EXPORT-DEMAND CONTROL

 dln_ExportDemand_TUR_jt =
   sum_d omega_jd0 * dln_Demand_jdt
********************************************************************/

use `dest_demand', clear

merge m:1 isic4 importer_key using `export_weights', keep(match) nogen

gen double weighted_demand_growth = omega_jd0 * dln_Demand_jdt
gen double omega_nonmissing = omega_jd0 if !missing(dln_Demand_jdt)

collapse (sum) dln_ExportDemand_TUR = weighted_demand_growth ///
    (sum) weight_covered = omega_nonmissing ///
    (count) n_destinations = weighted_demand_growth, by(isic4 year)
replace dln_ExportDemand_TUR = . if n_destinations == 0

save "$data_out/export_demand_tur_isic4_year.dta", replace
save `export_demand', replace

/********************************************************************
 8. COMBINE DEMAND CONTROLS
********************************************************************/

use `global_demand', clear
merge 1:1 isic4 year using `export_demand', nogen

label var dln_GlobalDemand_HI  "High-income global demand growth, excl. China/Turkey"
label var dln_ExportDemand_TUR "Turkey-weighted high-income export-demand growth"
label var weight_covered       "Base export weight with nonmissing destination demand growth"
label var n_destinations       "Base-weight destinations with nonmissing demand growth"

save "$data_out/demand_controls_isic4_year.dta", replace
save "$output_dir/demand_controls_isic4_year.dta", replace
save `demand_controls', replace
}

/********************************************************************
 9. MERGE CONTROLS INTO MAIN PANEL
********************************************************************/

use "$main_panel", clear

foreach v in firm_id isic4 year dln_mu change_IP output_IV Z_input ls_pre_filled post2016 {
    capture confirm variable `v'
    if _rc {
        di as error "Required main-panel variable `v' is missing."
        exit 111
    }
}

capture destring isic4, replace force
drop if missing(firm_id) | missing(isic4) | missing(year)

xtset firm_id year

* Rebuild common lagged controls only if absent. These names match the
* existing robustness do-files and data_ready_mec.dta.
capture confirm variable exporter
if _rc {
    capture confirm variable export_revenue
    if !_rc gen byte exporter = export_revenue > 0 if !missing(export_revenue)
}

capture confirm variable l_exporter
if _rc {
    capture confirm variable exporter
    if !_rc gen byte l_exporter = L.exporter
}

capture confirm variable llnsize
if _rc {
    capture confirm variable lnSize
    if !_rc gen double llnsize = L.lnSize
}

capture confirm variable lleverage
if _rc {
    capture confirm variable leverage
    if !_rc gen double lleverage = L.leverage
}

capture confirm variable lliquidity
if _rc {
    capture confirm variable liquidity_ratio_x_
    if !_rc gen double lliquidity = L.liquidity_ratio_x_
}

capture confirm variable l_age
if _rc {
    capture confirm variable age
    if !_rc gen double l_age = L.age
}

local X_lag_available
foreach v of global X_lag {
    capture confirm variable `v'
    if !_rc local X_lag_available `X_lag_available' `v'
    else di as txt "Warning: lagged control `v' is missing and will be omitted."
}
global X_lag "`X_lag_available'"
di as txt "Lagged controls used: $X_lag"

merge m:1 isic4 year using `demand_controls', keep(master match) nogen

save "$data_out/main_panel_with_demand_controls.dta", replace
save "$output_dir/main_panel_with_demand_controls.dta", replace
save `main_with_controls', replace

/********************************************************************
 10. IV ROBUSTNESS REGRESSIONS
********************************************************************/

use `main_with_controls', clear

eststo clear

* Baseline.
eststo base: ivreghdfe dln_mu ///
    (change_IP = output_IV) ///
    Z_input $X_lag ///
    c.ls_pre_filled##i.post2016 i.year ///
    if inrange(year, `est_start', `est_end'), ///
    absorb(isic4) vce(cluster isic4) partial(i.year)

* Add global high-income demand control.
eststo global_demand: ivreghdfe dln_mu ///
    (change_IP = output_IV) ///
    Z_input dln_GlobalDemand_HI $X_lag ///
    c.ls_pre_filled##i.post2016 i.year ///
    if inrange(year, `est_start', `est_end'), ///
    absorb(isic4) vce(cluster isic4) partial(i.year)

* Add Turkish export-demand control.
eststo export_demand: ivreghdfe dln_mu ///
    (change_IP = output_IV) ///
    Z_input dln_ExportDemand_TUR $X_lag ///
    c.ls_pre_filled##i.post2016 i.year ///
    if inrange(year, `est_start', `est_end'), ///
    absorb(isic4) vce(cluster isic4) partial(i.year)

* Add both demand controls.
eststo both_demand: ivreghdfe dln_mu ///
    (change_IP = output_IV) ///
    Z_input dln_GlobalDemand_HI dln_ExportDemand_TUR $X_lag ///
    c.ls_pre_filled##i.post2016 i.year ///
    if inrange(year, `est_start', `est_end'), ///
    absorb(isic4) vce(cluster isic4) partial(i.year)

esttab base global_demand export_demand both_demand ///
    using "$output_dir/iv_demand_controls.tex", replace ///
    se b(%9.3f) se(%9.3f) ///
    star(* 0.10 ** 0.05 *** 0.01) ///
    keep(change_IP Z_input dln_GlobalDemand_HI dln_ExportDemand_TUR) ///
    order(change_IP Z_input dln_GlobalDemand_HI dln_ExportDemand_TUR) ///
    stats(N r2, labels("Observations" "R-squared")) ///
    title("IV Robustness: Demand-Control Checks") ///
    addnotes("All regressions instrument change_IP with output_IV.", ///
             "Controls include lagged firm controls, Z_input, labor-share-by-post-2016 interaction, ISIC4 FE, and year FE.", ///
             "Standard errors are clustered by ISIC4.")

/********************************************************************
 11. PRE-TREND BALANCE CHECKS

 Question:
 Do sectors more exposed to the later China shifter already display
 differential pre-period trends?

 This version avoids absorb(isic4), because sector FE are inappropriate
 for a cross-sector pre-trend balance test after collapsing to sector-year.
********************************************************************/

use `main_with_controls', clear

*------------------------------------------------------------
* User timing
*------------------------------------------------------------
local pre_cutoff 2011
local post_start = `pre_cutoff' + 1

*------------------------------------------------------------
* Build list of available variables
*------------------------------------------------------------
local collapse_vars dln_mu change_IP output_IV Z_input

capture confirm variable sales_growth
if !_rc local collapse_vars `collapse_vars' sales_growth

capture confirm variable dln_sales
if !_rc local collapse_vars `collapse_vars' dln_sales

capture confirm variable dln_rev
if !_rc local collapse_vars `collapse_vars' dln_rev

capture confirm variable HHI_dom
if !_rc local collapse_vars `collapse_vars' HHI_dom

capture confirm variable CR4_dom
if !_rc local collapse_vars `collapse_vars' CR4_dom

capture confirm variable CR10_dom
if !_rc local collapse_vars `collapse_vars' CR10_dom

*------------------------------------------------------------
* Collapse to sector-year level
*------------------------------------------------------------
collapse (mean) `collapse_vars', by(isic4 year)

*------------------------------------------------------------
* Construct concentration growth if available
*------------------------------------------------------------
capture confirm variable HHI_dom
if !_rc {
    sort isic4 year
    by isic4: gen double dln_HHI_dom = log(HHI_dom) - log(HHI_dom[_n-1]) ///
        if year == year[_n-1] + 1 & HHI_dom > 0 & HHI_dom[_n-1] > 0
}

capture confirm variable CR4_dom
if !_rc {
    sort isic4 year
    by isic4: gen double dln_CR4_dom = log(CR4_dom) - log(CR4_dom[_n-1]) ///
        if year == year[_n-1] + 1 & CR4_dom > 0 & CR4_dom[_n-1] > 0
}

capture confirm variable CR10_dom
if !_rc {
    sort isic4 year
    by isic4: gen double dln_CR10_dom = log(CR10_dom) - log(CR10_dom[_n-1]) ///
        if year == year[_n-1] + 1 & CR10_dom > 0 & CR10_dom[_n-1] > 0
}

*------------------------------------------------------------
* Define pre/post
*------------------------------------------------------------
gen byte pre_period  = year <= `pre_cutoff'
gen byte post_period = year >= `post_start'

*------------------------------------------------------------
* Construct sector-level future China-shock intensity
* This is the object used to test pre-trends.
*------------------------------------------------------------
bys isic4: egen double outputIV_post_mean = mean(output_IV) if post_period == 1
bys isic4: egen double Zinput_post_mean   = mean(Z_input)  if post_period == 1

bys isic4: egen double outputIV_future = max(outputIV_post_mean)
bys isic4: egen double Zinput_future   = max(Zinput_post_mean)

drop outputIV_post_mean Zinput_post_mean

*------------------------------------------------------------
* Keep pre-period observations only
*------------------------------------------------------------
keep if pre_period == 1

eststo clear
local pre_models

*------------------------------------------------------------
* Helper logic:
* Use OLS with year FE, clustered by ISIC4.
* Do NOT absorb ISIC4.
*------------------------------------------------------------

* 1. Pre-period markup growth
capture confirm variable dln_mu
if !_rc {
    quietly count if !missing(dln_mu, outputIV_future, Zinput_future)
    if r(N) > 10 {
        capture noisily eststo pre_mu: reg dln_mu outputIV_future Zinput_future i.year, ///
            vce(cluster isic4)
        if !_rc local pre_models `pre_models' pre_mu
    }
}

* 2. Pre-period import-penetration growth
capture confirm variable change_IP
if !_rc {
    quietly count if !missing(change_IP, outputIV_future, Zinput_future)
    if r(N) > 10 {
        capture noisily eststo pre_ip: reg change_IP outputIV_future Zinput_future i.year, ///
            vce(cluster isic4)
        if !_rc local pre_models `pre_models' pre_ip
    }
}

* 3. Pre-period sales/revenue growth
capture confirm variable sales_growth
if !_rc {
    quietly count if !missing(sales_growth, outputIV_future, Zinput_future)
    if r(N) > 10 {
        capture noisily eststo pre_sales: reg sales_growth outputIV_future Zinput_future i.year, ///
            vce(cluster isic4)
        if !_rc local pre_models `pre_models' pre_sales
    }
}
else {
    capture confirm variable dln_sales
    if !_rc {
        quietly count if !missing(dln_sales, outputIV_future, Zinput_future)
        if r(N) > 10 {
            capture noisily eststo pre_sales: reg dln_sales outputIV_future Zinput_future i.year, ///
                vce(cluster isic4)
            if !_rc local pre_models `pre_models' pre_sales
        }
    }
    else {
        capture confirm variable dln_rev
        if !_rc {
            quietly count if !missing(dln_rev, outputIV_future, Zinput_future)
            if r(N) > 10 {
                capture noisily eststo pre_sales: reg dln_rev outputIV_future Zinput_future i.year, ///
                    vce(cluster isic4)
                if !_rc local pre_models `pre_models' pre_sales
            }
        }
    }
}

* 4. Pre-period concentration growth
capture confirm variable dln_HHI_dom
if !_rc {
    quietly count if !missing(dln_HHI_dom, outputIV_future, Zinput_future)
    if r(N) > 10 {
        capture noisily eststo pre_hhi: reg dln_HHI_dom outputIV_future Zinput_future i.year, ///
            vce(cluster isic4)
        if !_rc local pre_models `pre_models' pre_hhi
    }
}
else {
    capture confirm variable dln_CR4_dom
    if !_rc {
        quietly count if !missing(dln_CR4_dom, outputIV_future, Zinput_future)
        if r(N) > 10 {
            capture noisily eststo pre_hhi: reg dln_CR4_dom outputIV_future Zinput_future i.year, ///
                vce(cluster isic4)
            if !_rc local pre_models `pre_models' pre_hhi
        }
    }
    else {
        capture confirm variable dln_CR10_dom
        if !_rc {
            quietly count if !missing(dln_CR10_dom, outputIV_future, Zinput_future)
            if r(N) > 10 {
                capture noisily eststo pre_hhi: reg dln_CR10_dom outputIV_future Zinput_future i.year, ///
                    vce(cluster isic4)
                if !_rc local pre_models `pre_models' pre_hhi
            }
        }
    }
}

*------------------------------------------------------------
* Export table
*------------------------------------------------------------
if "`pre_models'" != "" {
    esttab `pre_models' using "$output_dir/pretrend_balance_outputIV.tex", replace ///
        se b(%9.3f) se(%9.3f) ///
        star(* 0.10 ** 0.05 *** 0.01) ///
        keep(outputIV_future Zinput_future) ///
        order(outputIV_future Zinput_future) ///
        stats(N r2, labels("Observations" "R-squared")) ///
        title("Pre-trend Balance Checks: Do Future China Shocks Predict Pre-period Outcomes?") ///
        addnotes("Each column is a sector-year pre-period outcome regression.", ///
                 "The main coefficient tests whether sectors more exposed to later China shocks already had differential pre-period trends.", ///
                 "Regressions include year fixed effects and cluster standard errors by ISIC4.")
}
else {
    di as txt "No pre-trend balance table exported: no eligible pre-period regressions were available."
}

log close


